# Generated by Django 5.2.1 on 2025-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="drink",
            options={"verbose_name": "飲料", "verbose_name_plural": "飲料"},
        ),
        migrations.AddField(
            model_name="drink",
            name="category",
            field=models.CharField(
                choices=[("tea", "茶類"), ("milk", "奶類"), ("other", "其他")],
                default="other",
                max_length=50,
                verbose_name="類別",
            ),
        ),
        migrations.AlterField(
            model_name="drink",
            name="description",
            field=models.TextField(verbose_name="介紹"),
        ),
        migrations.AlterField(
            model_name="drink",
            name="image_url",
            field=models.URLField(blank=True, verbose_name="圖片網址"),
        ),
        migrations.AlterField(
            model_name="drink",
            name="name",
            field=models.CharField(max_length=100, verbose_name="飲料名稱"),
        ),
    ]
